language: python
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
      env:
        - PYTHON_MAJOR_VERSION=2.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
    - os: linux
      dist: trusty
      python: 3.4
      env:
        - PYTHON_MAJOR_VERSION=3.4
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
            - python3-pip
    - os: linux
      dist: trusty
      python: 3.5
      env:
        - PYTHON_MAJOR_VERSION=3.5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
            - python3-pip
    - os: linux
      dist: trusty
      python: 3.6
      env:
        - PYTHON_MAJOR_VERSION=3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - git
            - libcurl4-openssl-dev
            - unzip
            - gcc-4.8
            - g++-4.8
            - cmake
            - gfortran
            - pandoc
            - python3-pip

    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=2.7
    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.4
    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.5
    - os: osx
      osx_image: xcode8.2
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.6

    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=2.7
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.4
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.5
    - os: osx
      osx_image: xcode8
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.6

    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=2.7
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.4
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.5
    - os: osx
      osx_image: xcode6.4
      language: generic
      env:
        - PYTHON_MAJOR_VERSION=3.6
before_install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      rvm get head --auto-dotfiles
      brew update;
      PYTHON_VERSION=$(pyenv install --list | grep "^$PYTHON_MAJOR_VERSION")
      pyenv install -s $PYTHON_VERSION
      pyenv global $PYTHON_VERSION
      # protoc
      pushd /tmp
      wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-osx-x86_64.zip
      unzip protoc-3.1.0-osx-x86_64.zip
      popd
      export PATH=/tmp/bin:$PATH
      # bazel
      brew install bazel
  fi
  if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      # protoc
      pushd /tmp
      wget https://github.com/google/protobuf/releases/download/v3.1.0/protoc-3.1.0-linux-x86_64.zip
      unzip protoc-3.1.0-linux-x86_64.zip
      popd
      export PATH=/tmp/bin:$PATH
      # bazel
      wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel_0.4.4-linux-x86_64.deb
      sudo dpkg -i bazel_0.4.4-linux-x86_64.deb
  fi
install:
- pip install -U pip setuptools wheel protobuf numpy
script:
- source travis_installer.sh
- python tests/python/test_scalar.py
deploy:
  provider: pypi
  user: zihaolucky
  password:
    secure: ZyEKpUw65IYCilD5vRuQRU0Ou5OlPj5TA/7ZZgDwwC012cnRnd54RHciHEnAf53QM9HWnBswmWGlnzicFYwcNMEM4YgSW0janoILfZJdtx5fCRETZ7lHLmGCxRkKbAkzYNKTxHmiqs8X19CKkalcOgc7/y4UDyARfk3OSpnIX2G9Is9s3Kr2DUyCI599k6nCI8ArTc/sEGE24vOp0Z/6b8g5CFXtqo2mSCREXmBQ6nXDj2mEKVCVtOE/N6ITlyTld+AYv59cGKls4y1TD2Vq4a/KMKxBzYrr0sqVX1+dw+SvRak3Nfv+jPgbrB94m/yv3j/MlDN4E5AdJW+BPJHXCIHy5IwhKBCXGS8IrMUTj2l/rkBe9hskALUnweSrKScHKUkieJLY/ns/oWYLSUgm46e+SRuQDtE5vYWrHq0wcvsBjDl5AMap0NcxdsvJM8xDiVkmPLwdJ5m/rrYWtp8sM9BFpEXSGZCauA7v8WfRe4xIJTtUxSdg23Nl76vsSLWLbqsQVuaRYXFmOw0Ct7aZZrfKauRDljrW1gTZ5nDhGWVLs97rJDTgd1L6UJELsy9x/B6PneQWgnahB1oZkzDz6u/+Csi0+QlRjp+x8qHxH8pNiiGnE9kvtM/wmu2/PRS+6Xzz1HdtC6N2xaaifrtZAH53E1j/dsVkAJC9G8uN1QE=
  distributions: bdist_wheel
  on:
    tags: true